/* Generated By:JavaCC: Do not edit this line. ParserPrologConstants.java */
package uniandes.lym.parserJavaCC.parserProlog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPrologConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW = 5;
  /** RegularExpression Id. */
  int Symbol1 = 6;
  /** RegularExpression Id. */
  int Symbol = 7;
  /** RegularExpression Id. */
  int Symbol2 = 8;
  /** RegularExpression Id. */
  int CH = 9;
  /** RegularExpression Id. */
  int QUOTED = 10;
  /** RegularExpression Id. */
  int CALL = 11;
  /** RegularExpression Id. */
  int FAIL = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int DIGIT = 14;
  /** RegularExpression Id. */
  int UPPER = 15;
  /** RegularExpression Id. */
  int LOWER = 16;
  /** RegularExpression Id. */
  int VAR = 17;
  /** RegularExpression Id. */
  int ATOM = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":-\"",
    "\"< >\"",
    "\"!\"",
    "\":=\"",
    "<CH>",
    "<QUOTED>",
    "\"call\"",
    "\",fail.\"",
    "<INT>",
    "<DIGIT>",
    "<UPPER>",
    "<LOWER>",
    "<VAR>",
    "<ATOM>",
    "\"(\"",
    "\")\"",
    "\"=..\"",
    "\",\"",
    "\".\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
